### ISSUE TITLE
Add Jira automation to open tasks for every issue created 

### ISSUE THREAD

**Issue by agileshaw** [canonical/bootstack-actions#38] opened 2023-10-30 16:58 UTC
Adding jira automation (a workflow like [this](https://github.com/canonical/snap-tempest/blob/main/.github/workflows/issues_to_jira.yaml)) enables automatic task creation for every issue opened/closed in the repo.

**Comment by rgildein** [comment] 2023-11-02 10:53
duplicate of : #12

**Closed by rgildein** 2023-11-02 10:53 UTC
Labels: enhancement
